### ISSUE TITLE
Message board:  delete button on posts deletes entire topic.

### ISSUE THREAD

**Issue by ratkins5** [whythawk/hrd#90] opened 2015-02-24 08:39 UTC
Hit the 'delete' button on the first comment in the topic 'Test Topic' that I had created earlier, entire topic deleted.

Created a new topic to replicate this, generated server error: https://hrdrelocation.eu/en/forum/post/21/delete
![screen shot 2015-02-24 at 08 39 16](https://cloud.githubusercontent.com/assets/9843434/6345721/ab7c4f68-bc00-11e4-8c23-c3e4b038f3f2.png)

**Comment by ratkins5** [comment] 2015-02-24 08:43
Further testing this, deleting subsequent posts (i.e. not the first post in the topic) generates the above server error, but when you go back in to look at the topic the post has in fact been deleted.  Thus, it seems that deleting the first post deletes the entire topic, but deleting subsequent posts returns the 'server error' screen but despite that does in fact work as expected.

**Comment by tobes** [comment] 2015-02-24 11:43
Ok,

The problem is actually because the topic has a post that was reported.  This was causing various problems but should now be fixed on the live site.

If you want to do some testing creating topics, categories etc and reporting a post and then deleting topic/cat should now work but some extra testing would be good

**Closed by tobes** 2015-02-24 11:43 UTC

**Comment by tobes** [comment] 2015-02-24 11:46
ok the cat delete still needs a little work

**Comment by ratkins5** [comment] 2015-02-24 14:58
Still seems to delete the topic if I delete the first post in that topic.  I'll work on the assumption that the cat delete is still under development, but maybe this should be open till we know it's fully fixed?

**Comment by tobes** [comment] 2015-02-24 14:59
This is intentional as the whole topic is about the first thread

**Comment by ratkins5** [comment] 2015-02-24 15:00
Oh I see; of course.
